routes/web.php
<?php

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/regex', 'RegexController@index');

Route::middleware(['auth'])->group(function () {

    Route::delete('cancelFriendRequest', 'UsersController@cancelFriendRequest')->name('users.cancelFriendRequest');
    Route::post('denyFriend', 'UsersController@denyFriend')->name('users.denyFriend');
    Route::delete('deleteFriend', 'UsersController@deleteFriend')->name('users.deleteFriend');
    Route::post('addToFriends', 'UsersController@addToFriends')->name('users.addToFriends');
    Route::post('acceptFriend', 'UsersController@acceptFriend')->name('users.acceptFriend');
    Route::get('friends', 'UsersController@friendListInfo')->name('users.friends');

    Route::put('comments/update', 'CommentsController@update')->name('comments.update');
    Route::resource('comments', 'CommentsController')->only(['store', 'destroy']);

    Route::get('threads/{thread_id}/participants/search', 'SearchController@findParticipants')->name('search.participants');
    Route::delete('threads/{thread_id}/kickMember/{user_id}', 'MessagesController@kickFromThread')->name('messages.kickMember');
    Route::get('threads/{thread_id}/participants', 'MessagesController@currentParticipants')->name('messages.currentParticipants');
    Route::delete('threads/{thread_id}', 'MessagesController@deleteThread')->name('threads.delete');
    Route::delete('messages/{id}', 'MessagesController@destroy')->name('messages.destroy');
    Route::put('messages', 'MessagesController@edit')->name('messages.edit');
    Route::group(['prefix' => 'messages'], function () {
        Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
        Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
        Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
        Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
        Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
    });
});

Route::group(['middleware' => ['auth', 'verified']], function() {

    Route::resource('companies', 'CompaniesController')->except(['index', 'show']);

    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::post('projects/addUser', 'ProjectsController@addUser')->name('projects.addUser');
    Route::delete('projects/member/{project_id}/{user_id}', 'ProjectsController@deleteMember')->name('projects.deleteMember');
    Route::resource('projects', 'ProjectsController')->except(['index', 'show']);

    Route::get('tasks/create/{project_id?}', 'TasksController@create');
    Route::post('tasks/addUser', 'TasksController@addUser')->name('tasks.addUser');
    Route::delete('tasks/member/{task_id}/{user_id}', 'TasksController@deleteMember')->name('tasks.deleteMember');
    Route::resource('tasks', 'TasksController')->except(['index', 'show']);
});

Route::group(['middleware' => ['auth', 'verified', 'admin']], function() {
    Route::get('companies/all', 'CompaniesController@all')->name('admin.companies');
    Route::get('projects/all', 'ProjectsController@all')->name('admin.projects');
    Route::get('tasks/all', 'TasksController@all')->name('admin.tasks');
    Route::delete('users/{user}', 'UsersController@destroy')->name('users.destroy');
    Route::get('users/all', 'UsersController@all')->name('admin.users');
    Route::get('comments/all', 'CommentsController@all')->name('admin.comments');
});

Route::get('search', 'SearchController@search')->name('search');

Route::get('companies', 'CompaniesController@index')->name('companies.index');
Route::get('companies/{company}', 'CompaniesController@show')->name('companies.show');

Route::get('projects', 'ProjectsController@index')->name('projects.index');
Route::get('projects/{project}', 'ProjectsController@show')->name('projects.show');

Route::get('tasks', 'TasksController@index')->name('tasks.index');
Route::get('tasks/{task}', 'TasksController@show')->name('tasks.show');

Route::get('users/{user}', 'UsersController@show')->name('users.show');

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = [
        'name',
        'description',
        'company_id',
        'user_id',
    ];

    public function tasks()
    {
        return $this->hasMany(Task::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    public static function findByUserId($user_id)
    {
        $projects = Project::where('user_id', $user_id)->get();
        return $projects;
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProjectsRequest;
use App\Mail\UserAttachedToProject;
use App\Mail\UserRemovedFromProject;
use App\Models\Comment;
use App\Models\Company;
use App\Models\Project;
use App\Models\User;
use App\Models\ProjectUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

class ProjectsController extends Controller
{
    public function deleteMember($project_id, $user_id)
    {
        ProjectUser::findOneByUserIdAndProjectId($user_id, $project_id)->delete();

        $user = User::find($user_id);
        $project = Project::find($project_id);
        Mail::to($user)->send(new UserRemovedFromProject($project));

        return response()->json([
            'message' => 'Project member was removed'
        ]);
    }

    public function addUser(Request $request)
    {
        $project = Project::find($request->input('project_id'));
        if (Auth::id() == $project->user_id) {

            $user = User::findOneByEmail($request->input('email'));

            if (!$user) {
                return redirect()->route('projects.show', ['project' => $project])
                    ->with('errors', $request->input('email').' doesnt exist');
            }

            $projectUser = ProjectUser::findOneByUserIdAndProjectId($user->id, $project->id);

            if ($projectUser) {
                return redirect()->route('projects.show', ['project' => $project])
                    ->with('errors', $request->input('email') . ' is already a member of this Project');
            }

            $project->users()->attach($user->id);
            Mail::to($user)->send(new UserAttachedToProject($project));

            return redirect()->route('projects.show', ['project' => $project])
                ->with('success', $request->input('email') . ' was added to Project successfully and was notified via email');
        }

        return redirect()->route('projects.show', ['project' => $project])
            ->with('errors', 'Invalid action');
    }

    public function all()
    {
        $projects = Project::all();
        return view('admin.projects', ['projects' => $projects]);
    }

    public function index()
    {
        $projects = null;
        if (Auth::check()) {
            $projects = Project::findByUserId(Auth::id());
        }
        return view('projects.index', ['projects' => $projects]);
    }

    public function create($company_id = null)
    {
        $companies = null;
        if (!$company_id) {
            $companies = Company::findByUserId(Auth::id());
        }

        return view('projects.create', ['company_id' => $company_id, 'companies' => $companies]);
    }

    public function store(ProjectsRequest $request)
    {
        $request->validated();

        $project = Project::create([
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'company_id' => $request->input('company_id'),
            'user_id' => Auth::user()->id
        ]);

        if ($project) {
            return redirect()->route('projects.show', ['project' => $project])
                ->with('success' , 'Project created successfully');
        }

        return back()->withInput()->with('errors', 'Error creating new Project');
    }

    public function show(Project $project)
    {
        $comments = Comment::findByIdAndType('App\Models\Project', $project->id, 4);
        $creator = User::find($project->user_id);
        $company = Company::find($project->company_id);

        return view('projects.show', ['project' => $project, 'comments' => $comments, 'creator' => $creator, 'company' => $company]);
    }

    public function edit(Project $project)
    {
        return view('projects.edit', ['project' => $project]);
    }

    public function update(ProjectsRequest $request, Project $project)
    {
        $request->validated();

        $project->update([
            'name'=> $request->input('name'),
            'description'=> $request->input('description')
        ]);

        return redirect()->route('projects.show', ['project'=> $project])
            ->with('success' , 'Project updated successfully');
    }

    public function destroy(Project $project)
    {
        $project->delete();
        Comment::deleteByTypeAndId('App\Models\Project', $project->id);

        if (Auth::user()->role_id == 1) {
            return redirect()->route('admin.projects')->with('success' , 'Project deleted successfully');
        }
        return redirect()->route('projects.index')->with('success' , 'Project deleted successfully');
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9 ">
        <h3 class="text-center">Create new Project</h3>
            <form method="post" action="{{ route('projects.store') }}">
                @csrf

                <div class="form-group">
                    <label for="project-name">Name:</label>
                    <input   placeholder="Enter name"
                             id="project-name"
                             required
                             name="name"
                             spellcheck="false"
                             class="form-control form-control-lg"
                    />
                </div>

                @if($companies == null)
                    <input
                        class="form-control form-control-lg"
                        type="hidden"
                        name="company_id"
                        value="{{ $company_id }}"
                    />

                @endif

                @if($companies != null && $company_id != null)
                    <div class="form-group">
                        <label for="company-content">Select company:</label>

                        <select name="company_id" class="form-control form-control-lg" >
                            @foreach($companies as $company)
                                <option value="{{$company->id}}"> {{$company->name}} </option>
                            @endforeach
                        </select>
                    </div>
                @endif

                <div class="form-group">
                    <label for="project-content">Description:</label>
                    <textarea placeholder="Enter description"
                              id="project-content"
                              name="description"
                              rows="5" spellcheck="false"
                              class="form-control form-control-lg ">
                    </textarea>
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-primary btn-block"
                           value="Submit"/>
                </div>

            </form>
    </div>

    <div class="col-sm-3">
        <ul class="list-group">
            <h4>Actions: </h4>
            <li class="list-group-item"><a href="/projects">All Projects</a></li>
        </ul>
    </div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9">
            <form method="post" action="{{ route('projects.update', [$project->id]) }}">
                @csrf

                @method('put')

                <div class="form-group">
                    <label for="project-name">Name:</label>
                    <input   placeholder="Enter name"
                             id="project-name"
                             required
                             name="name"
                             spellcheck="false"
                             class="form-control form-control-lg"
                             value="{{ $project->name }}"
                    />
                </div>

                <div class="form-group">
                    <label for="project-content">Description:</label>
                    <textarea placeholder="Enter description"
                              id="project-content"
                              name="description"
                              rows="5" spellcheck="false"
                              class="form-control form-control-lg">{{ $project->description }}</textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary btn-block"
                           value="Submit"/>
                </div>
            </form>
    </div>

    <div class="col-sm-3">
        <ul class="list-group">
            <h4>Actions: </h4>
            <li class="list-group-item"><a href="/projects/{{ $project->id }}">View Project</a></li>
            <li class="list-group-item"><a href="/projects">My Projects</a></li>
        </ul>
    </div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-6 col-lg-6 center">
        <div class="card">
            <div class="card-header text-center text-white bg-primary"> Projects <a class="btn btn-primary" href="/projects/create">Create new</a></div>
            <div class="card-body">
                <ul class="list-group">
                    @if (!is_null($projects) && count($projects) > 0)
                        @foreach($projects as $project)
                            <li class="list-group-item">
                                <a href="/projects/{{ $project->id }}"> {{ $project->name }} </a>
                            </li>
                        @endforeach
                    @else
                        <li class="list-group-item">
                            <p class="text-center">No Projects yet</p>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9">
        <div class="jumbotron text-center">
            <h1>{{ $project->name }}</h1>
            <p class="lead">{{ $project->description }}</p>
            <p class="text-success">created at {{ $project->created_at }}</p>
            <p class="lead">by <a href="/users/{{ $creator->id }}">{{ $creator->email }}</a> </p>
            @if ($company)
                <p class="lead">Company title: <a href="/companies/{{ $company->id }}">{{ $company->name }}</a>
                </p>
            @endif
        </div>

        <div class="row">
            @foreach($project->tasks as $task)
                <div class="col-sm-4">
                    <h2>{{ $task->name }}</h2>
                    <p class="text-success">Duration: {{ $task->duration }}</p>
                    <p><a class="btn btn-primary btn-block" href="/tasks/{{ $task->id }}" role="button">View Task</a>
                    </p>
                </div>
            @endforeach
        </div>

        @include('partials.comments')

        @include('partials.new-comment-form', ["type" => "App\Models\Project", "id" => $project->id])

    </div>


    <div class="col-sm-3">
        <div class="sidebar-module">
            <h4>Actions: </h4>
            <ol class="list-unstyled">
                @if (Auth::check() && ($project->user_id == Auth::user()->id || Auth::user()->role_id == 1))
                    <li><a href="/projects/{{ $project->id }}/edit"><i class="fas fa-edit"></i> Edit</a></li>
                    <li><a href="/tasks/create/{{ $project->id }}"><i class="fas fa-tasks"></i> Add Task</a></li>
                @endif
                <li><a href="/projects/create"><i class="fas fa-plus-circle"></i> Create new Project</a></li>

                <li><a href="/projects"><i class="fas fa-briefcase"></i> My projects</a></li>
                <br>
                @if (Auth::check() && ($project->user_id == Auth::user()->id || Auth::user()->role_id == 1))
                    <li>
                        <a href="#" class="js-delete">
                            <i class="fas fa-trash"></i> Delete
                        </a>

                        <form id="delete-form" action="{{ route('projects.destroy', [$project->id]) }}"
                              method="POST" class="hidden">
                            @method('delete')
                            @csrf
                        </form>
                    </li>
                @endif
            </ol>
            @if (Auth::check() && ($project->user_id == Auth::user()->id || Auth::user()->role_id == 1))
                <h5>Add members:</h5>
                <form id="add-user" action="{{ route('projects.addUser') }}" method="POST">
                    @csrf

                    <div class="input-group">
                        <input class="form-control" name="project_id" value="{{ $project->id }}" type="hidden">
                        <input type="text" class="form-control" id="email" required name="email"
                               placeholder="Email">

                        <span class="input-group-btn">
                            <button class="btn btn-primary" type="submit">Add!</button>
                        </span>
                    </div>
                </form>
                <br>
            @endif
            <h5>Current members:</h5>
            <ul class="list-group">
                @if (count($project->users) > 0)
                    @foreach($project->users as $user)
                        <li class="list-group-item "><a href="/users/{{ $user->id }}">{{ $user->email }}</a>
                            @if (Auth::check() && ($project->user_id == Auth::user()->id || Auth::user()->role_id == 1))
                                <button type="button" class="btn btn-danger btn-sm js-delete-project-member float-right"
                                        data-project_id="{{ $project->id }}" data-user_id="{{ $user->id  }}">
                                    Remove
                                </button>
                            @endif
                        </li>
                    @endforeach
                @else
                    <h6 class="text-muted">No active members yet</h6>
                @endif
            </ul>

        </div>
    </div>
@endsection