routes/web.php
<?php

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/regex', 'RegexController@index');

Route::middleware(['auth'])->group(function () {

    Route::delete('cancelFriendRequest', 'UsersController@cancelFriendRequest')->name('users.cancelFriendRequest');
    Route::post('denyFriend', 'UsersController@denyFriend')->name('users.denyFriend');
    Route::delete('deleteFriend', 'UsersController@deleteFriend')->name('users.deleteFriend');
    Route::post('addToFriends', 'UsersController@addToFriends')->name('users.addToFriends');
    Route::post('acceptFriend', 'UsersController@acceptFriend')->name('users.acceptFriend');
    Route::get('friends', 'UsersController@friendListInfo')->name('users.friends');

    Route::put('comments/update', 'CommentsController@update')->name('comments.update');
    Route::resource('comments', 'CommentsController')->only(['store', 'destroy']);

    Route::get('threads/{thread_id}/participants/search', 'SearchController@findParticipants')->name('search.participants');
    Route::delete('threads/{thread_id}/kickMember/{user_id}', 'MessagesController@kickFromThread')->name('messages.kickMember');
    Route::get('threads/{thread_id}/participants', 'MessagesController@currentParticipants')->name('messages.currentParticipants');
    Route::delete('threads/{thread_id}', 'MessagesController@deleteThread')->name('threads.delete');
    Route::delete('messages/{id}', 'MessagesController@destroy')->name('messages.destroy');
    Route::put('messages', 'MessagesController@edit')->name('messages.edit');
    Route::group(['prefix' => 'messages'], function () {
        Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
        Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
        Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
        Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
        Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
    });
});

Route::group(['middleware' => ['auth', 'verified']], function() {

    Route::resource('companies', 'CompaniesController')->except(['index', 'show']);

    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::post('projects/addUser', 'ProjectsController@addUser')->name('projects.addUser');
    Route::delete('projects/member/{project_id}/{user_id}', 'ProjectsController@deleteMember')->name('projects.deleteMember');
    Route::resource('projects', 'ProjectsController')->except(['index', 'show']);

    Route::get('tasks/create/{project_id?}', 'TasksController@create');
    Route::post('tasks/addUser', 'TasksController@addUser')->name('tasks.addUser');
    Route::delete('tasks/member/{task_id}/{user_id}', 'TasksController@deleteMember')->name('tasks.deleteMember');
    Route::resource('tasks', 'TasksController')->except(['index', 'show']);
});

Route::group(['middleware' => ['auth', 'verified', 'admin']], function() {
    Route::get('companies/all', 'CompaniesController@all')->name('admin.companies');
    Route::get('projects/all', 'ProjectsController@all')->name('admin.projects');
    Route::get('tasks/all', 'TasksController@all')->name('admin.tasks');
    Route::delete('users/{user}', 'UsersController@destroy')->name('users.destroy');
    Route::get('users/all', 'UsersController@all')->name('admin.users');
    Route::get('comments/all', 'CommentsController@all')->name('admin.comments');
});

Route::get('search', 'SearchController@search')->name('search');

Route::get('companies', 'CompaniesController@index')->name('companies.index');
Route::get('companies/{company}', 'CompaniesController@show')->name('companies.show');

Route::get('projects', 'ProjectsController@index')->name('projects.index');
Route::get('projects/{project}', 'ProjectsController@show')->name('projects.show');

Route::get('tasks', 'TasksController@index')->name('tasks.index');
Route::get('tasks/{task}', 'TasksController@show')->name('tasks.show');

Route::get('users/{user}', 'UsersController@show')->name('users.show');

resources/views/admin/comments.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-12 col-sm-12 col-xs-12">
       @include ('partials.comments')
    </div>
@endsection

resources/views/admin/companies.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-6 col-lg-6 center">
        <div class="card">
            <div class="card-header text-center text-white bg-primary"> Companies <a class="btn btn-primary" href="/companies/create">Create new</a></div>
            <div class="card-body">
                <ul class="list-group">
                    @if (count($companies) > 0)
                        @foreach($companies as $company)
                            <li class="list-group-item">
                                <a href="/companies/{{ $company->id }}">{{ $company->name }}</a>
                                <button type="button" class="btn btn-danger btn-sm float-right mr-left-8 js-delete">Delete</button>
                                <button type="button" class="btn btn-dark btn-sm float-right "><a href="/companies/{{ $company->id }}/edit" class="text-white">Edit</a></button>

                                <form id="delete-form" action="{{ route('companies.destroy', [$company->id]) }}"
                                      method="POST" class="hidden">
                                      @method('delete')
                                    @csrf
                                </form>
                            </li>
                        @endforeach
                    @else
                        <li class="list-group-item">
                            <p class="text-center">No Companies yet</p>
                        </li>
                    @endif
                </ul>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/projects.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-6 col-lg-6 center">
        <div class="card">
            <div class="card-header text-center text-white bg-primary"> Projects <a class="pull-right btn btn-primary" href="/projects/create">Create new</a></div>
            <div class="card-body">
                <ul class="list-group">
                    @if (count($projects) > 0)
                        @foreach($projects as $project)
                            <li class="list-group-item">
                                <a href="/projects/{{ $project->id }}">{{ $project->name }}</a>
                                <button type="button" class="btn btn-danger btn-sm float-right mr-left-8 js-delete">Delete</button>
                                <button type="button" class="btn btn-dark btn-sm float-right "><a href="/projects/{{ $project->id }}/edit" class="text-white">Edit</a></button>

                                <form id="delete-form" action="{{ route('projects.destroy', [$project->id]) }}"
                                      method="POST" class="hidden">
                                    @method('delete')
                                    @csrf
                                </form>
                            </li>
                        @endforeach
                    @else
                        <li class="list-group-item">
                            <p class="text-center">No Projects yet</p>
                        </li>
                    @endif
                </ul>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/tasks.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-6 col-lg-6 center">
        <div class="card">
            <div class="card-header text-center text-white bg-primary"> Tasks <a class="pull-right btn btn-primary" href="/tasks/create">Create new</a></div>
            <div class="card-body">
                <ul class="list-group">
                    @if (count($tasks) > 0)
                        @foreach($tasks as $task)
                            <li class="list-group-item">
                                <a href="/tasks/{{ $task->id }}">{{ $task->name }}</a>
                                <button type="button" class="btn btn-danger btn-sm float-right mr-left-8 js-delete">Delete</button>
                                <button type="button" class="btn btn-dark btn-sm float-right "><a href="/tasks/{{ $task->id }}/edit" class="text-white">Edit</a></button>

                                <form id="delete-form" action="{{ route('tasks.destroy', [$task->id]) }}"
                                      method="POST" class="hidden">
                                    @method('delete')
                                    @csrf
                                </form>
                            </li>
                        @endforeach
                    @else
                        <li class="list-group-item">
                            <p class="text-center">No Tasks yet</p>
                        </li>
                    @endif
                </ul>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/users.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-6 col-lg-6 center">
        <div class="card">
            <div class="card-header text-center text-white bg-primary"> Users</div>
            <div class="card-body">
                <ul class="list-group">
                    @if (count($users) > 0)
                        @foreach($users as $user)
                            <li class="list-group-item">
                                <a href="/users/{{ $user->id }}">{{ $user->name }}</a>
                                <button type="button" class="btn btn-danger btn-sm float-right mr-left-8 js-delete-user" data-id="{{ $user->id }}">
                                    Delete
                                </button>
                            </li>
                        @endforeach
                    @else
                        <li class="list-group-item">
                            <p class="text-center">No Users registered</p>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
@endsection