routes/web.php
<?php

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/regex', 'RegexController@index');

Route::middleware(['auth'])->group(function () {

    Route::delete('cancelFriendRequest', 'UsersController@cancelFriendRequest')->name('users.cancelFriendRequest');
    Route::post('denyFriend', 'UsersController@denyFriend')->name('users.denyFriend');
    Route::delete('deleteFriend', 'UsersController@deleteFriend')->name('users.deleteFriend');
    Route::post('addToFriends', 'UsersController@addToFriends')->name('users.addToFriends');
    Route::post('acceptFriend', 'UsersController@acceptFriend')->name('users.acceptFriend');
    Route::get('friends', 'UsersController@friendListInfo')->name('users.friends');

    Route::put('comments/update', 'CommentsController@update')->name('comments.update');
    Route::resource('comments', 'CommentsController')->only(['store', 'destroy']);

    Route::get('threads/{thread_id}/participants/search', 'SearchController@findParticipants')->name('search.participants');
    Route::delete('threads/{thread_id}/kickMember/{user_id}', 'MessagesController@kickFromThread')->name('messages.kickMember');
    Route::get('threads/{thread_id}/participants', 'MessagesController@currentParticipants')->name('messages.currentParticipants');
    Route::delete('threads/{thread_id}', 'MessagesController@deleteThread')->name('threads.delete');
    Route::delete('messages/{id}', 'MessagesController@destroy')->name('messages.destroy');
    Route::put('messages', 'MessagesController@edit')->name('messages.edit');
    Route::group(['prefix' => 'messages'], function () {
        Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
        Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
        Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
        Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
        Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
    });
});

Route::group(['middleware' => ['auth', 'verified']], function() {

    Route::resource('companies', 'CompaniesController')->except(['index', 'show']);

    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::post('projects/addUser', 'ProjectsController@addUser')->name('projects.addUser');
    Route::delete('projects/member/{project_id}/{user_id}', 'ProjectsController@deleteMember')->name('projects.deleteMember');
    Route::resource('projects', 'ProjectsController')->except(['index', 'show']);

    Route::get('tasks/create/{project_id?}', 'TasksController@create');
    Route::post('tasks/addUser', 'TasksController@addUser')->name('tasks.addUser');
    Route::delete('tasks/member/{task_id}/{user_id}', 'TasksController@deleteMember')->name('tasks.deleteMember');
    Route::resource('tasks', 'TasksController')->except(['index', 'show']);
});

Route::group(['middleware' => ['auth', 'verified', 'admin']], function() {
    Route::get('companies/all', 'CompaniesController@all')->name('admin.companies');
    Route::get('projects/all', 'ProjectsController@all')->name('admin.projects');
    Route::get('tasks/all', 'TasksController@all')->name('admin.tasks');
    Route::delete('users/{user}', 'UsersController@destroy')->name('users.destroy');
    Route::get('users/all', 'UsersController@all')->name('admin.users');
    Route::get('comments/all', 'CommentsController@all')->name('admin.comments');
});

Route::get('search', 'SearchController@search')->name('search');

Route::get('companies', 'CompaniesController@index')->name('companies.index');
Route::get('companies/{company}', 'CompaniesController@show')->name('companies.show');

Route::get('projects', 'ProjectsController@index')->name('projects.index');
Route::get('projects/{project}', 'ProjectsController@show')->name('projects.show');

Route::get('tasks', 'TasksController@index')->name('tasks.index');
Route::get('tasks/{task}', 'TasksController@show')->name('tasks.show');

Route::get('users/{user}', 'UsersController@show')->name('users.show');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
        'id',
        'name',
        'description',
        'user_id',
    ];

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function projects() {
        return $this->hasMany(Project::class);
    }

    public function comments() {
        return $this->morphMany(Comment::class, 'commentable');
    }

    public static function findByUserId($user_id)
    {
        $companies = Company::where('user_id', $user_id)->get();
        return $companies;
    }

    public static function createOne($name, $description, $user_id)
    {
        $company = Company::create([
            'name' => $name,
            'description' => $description,
            'user_id' => $user_id
        ]);

        return $company;
    }
}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CompanyRequest;
use App\Models\Comment;
use App\Models\Company;;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

class CompaniesController extends Controller
{
    public function all()
    {
        $companies = Company::all();
        return view('admin.companies', ['companies' => $companies]);
    }

    public function index()
    {
        $companies = null;
        if (Auth::check()) {
            $companies = Company::findByUserId(Auth::id());
        }
        return view('companies.index', ['companies' => $companies]);
    }

    public function create()
    {
        return view('companies.create');
    }

    public function store(CompanyRequest $request)
    {
        $request->validated();
        $company = Company::createOne($request->input('name'), $request->input('description'), Auth::id());

        return redirect()->route('companies.show', ['company' => $company])
            ->with('success', 'Company created successfully');
    }

    public function show(Company $company)
    {
        $itemsPerPage = 4;
        $comments = Comment::findByIdAndType('App\Models\Company', $company->id, $itemsPerPage);
        $creator = User::find($company->user_id);

        return view('companies.show', ['company' => $company, 'comments' => $comments, 'creator' => $creator]);
    }

    public function edit(Company $company)
    {
        return view('companies.edit', ['company' => $company]);
    }

    public function update(CompanyRequest $request, Company $company)
    {
        $request->validated();

        $company->update([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
            ]);

        return redirect()->route('companies.show', ['company' => $company])
            ->with('success', 'Company updated successfully');
    }

    public function destroy(Company $company)
    {
        $company->delete();
        Comment::deleteByTypeAndId('App\Models\Company', $company->id);

        if (Auth::user()->role_id == 1) {
            return redirect()->route('admin.companies')->with('success' , 'Company deleted successfully');
        }
        return redirect()->route('companies.index')->with('success' , 'Company deleted successfully');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9">
        <h3 class="text-center">Create new Company</h3>
            <form method="post" action="{{ route('companies.store') }}">
                @csrf

                <div class="form-group">
                    <label for="company-name">Name:</label>
                    <input   placeholder="Enter name"
                             id="company-name"
                             required
                             name="name"
                             spellcheck="false"
                             class="form-control form-control-lg"
                    />
                </div>

                <div class="form-group">
                    <label for="company-content">Description:</label>
                    <textarea placeholder="Enter description"
                              id="company-content"
                              name="description"
                              rows="5" spellcheck="false"
                              class="form-control form-control-lg">
                    </textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary btn-block"
                           value="Submit"/>
                </div>
            </form>
    </div>

    <div class="col-sm-3">
        <ul class="list-group">
            <h4>Actions: </h4>
            <li class="list-group-item"><a href="/companies">All Companies</a></li>
        </ul>
    </div>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9">
            <form method="post" action="{{ route('companies.update', [$company->id]) }}">
                @csrf

                @method('put')

                <div class="form-group">
                    <label for="company-name">Name:</label>
                    <input   placeholder="Enter name"
                             id="company-name"
                             required
                             name="name"
                             spellcheck="false"
                             class="form-control form-control-lg"
                             value="{{ $company->name }}"
                    />
                </div>

                <div class="form-group">
                    <label for="company-content">Description:</label>
                    <textarea placeholder="Enter description"
                              id="company-content"
                              name="description"
                              rows="5" spellcheck="false"
                              class="form-control form-control-lg">{{ $company->description }}
                    </textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary btn-block"
                           value="Submit"/>
                </div>
            </form>
    </div>

    <div class="col-sm-3">
        <ul class="list-group">
            <h4>Actions: </h4>
            <li class="list-group-item"><a href="/companies/{{ $company->id }}">View Company</a></li>
            <li class="list-group-item"><a href="/companies">All Companies</a></li>
        </ul>
    </div>

@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-6 col-lg-6 center">
        <div class="card">
            <div class="card-header text-center text-white bg-primary"> Companies <a class="btn btn-primary" href="/companies/create">Create new</a></div>
            <div class="card-body">
                <ul class="list-group">
                    @if (!is_null($companies) && count($companies) > 0)
                        @foreach($companies as $company)
                            <li class="list-group-item">
                                <a href="/companies/{{ $company->id }}"> {{ $company->name }} </a>
                            </li>
                        @endforeach
                    @else
                        <li class="list-group-item">
                            <p class="text-center">No Companies yet</p>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9">
        <div class="jumbotron text-center">
            <h1>{{ $company->name }}</h1>
            <p class="lead">{{ $company->description }}</p>
            <p class="text-success">created at {{ $company->created_at }}</p>
            <p class="lead">by <a href="/users/{{ $creator->id }}">{{ $creator->email }}</a> </p>
        </div>

        <div class="row">
            @foreach($company->projects as $project)
                <div class="col-sm-4">
                    <h2>{{ $project->name }}</h2>
                    <p class="text-success js-text-truncate">{{ $project->description }}</p>
                    <p><a class="btn btn-primary btn-block" href="/projects/{{ $project->id }}" role="button">View Project</a></p>
                </div>
            @endforeach
        </div>

        @include('partials.comments')

        @include('partials.new-comment-form', ["type" => "App\Models\Company", "id" => $company->id])

    </div>

    <div class="col-sm-3">
        <h4>Actions: </h4>
        <ol class="list-unstyled">
            @if (Auth::check() && ($company->user_id == Auth::user()->id || Auth::user()->role_id == 1))
                <li><a href="/companies/{{ $company->id }}/edit"><i class="fas fa-edit"></i> Edit</a></li>
                <li><a href="/projects/create/{{ $company->id }}"><i class="fas fa-briefcase"></i> Add Project</a></li>
            @endif
            <li><a href="/companies/create"><i class="fas fa-plus-circle"></i> Create new Company</a></li>

            <li><a href="/companies"><i class="fas fa-building"></i> My Companies</a></li>
            <br>
                @if (Auth::check() && ($company->user_id == Auth::user()->id || Auth::user()->role_id == 1))
                <li>
                    <a href="#" class="js-delete">
                        <i class="fas fa-trash"></i> Delete
                    </a>

                    <form id="delete-form" action="{{ route('companies.destroy', [$company->id]) }}"
                          method="POST" class="hidden">
                        @method('delete')
                        @csrf
                    </form>
                </li>
            @endif
        </ol>
    </div>

@endsection