routes/web.php
<?php

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/regex', 'RegexController@index');

Route::middleware(['auth'])->group(function () {

    Route::delete('cancelFriendRequest', 'UsersController@cancelFriendRequest')->name('users.cancelFriendRequest');
    Route::post('denyFriend', 'UsersController@denyFriend')->name('users.denyFriend');
    Route::delete('deleteFriend', 'UsersController@deleteFriend')->name('users.deleteFriend');
    Route::post('addToFriends', 'UsersController@addToFriends')->name('users.addToFriends');
    Route::post('acceptFriend', 'UsersController@acceptFriend')->name('users.acceptFriend');
    Route::get('friends', 'UsersController@friendListInfo')->name('users.friends');

    Route::put('comments/update', 'CommentsController@update')->name('comments.update');
    Route::resource('comments', 'CommentsController')->only(['store', 'destroy']);

    Route::get('threads/{thread_id}/participants/search', 'SearchController@findParticipants')->name('search.participants');
    Route::delete('threads/{thread_id}/kickMember/{user_id}', 'MessagesController@kickFromThread')->name('messages.kickMember');
    Route::get('threads/{thread_id}/participants', 'MessagesController@currentParticipants')->name('messages.currentParticipants');
    Route::delete('threads/{thread_id}', 'MessagesController@deleteThread')->name('threads.delete');
    Route::delete('messages/{id}', 'MessagesController@destroy')->name('messages.destroy');
    Route::put('messages', 'MessagesController@edit')->name('messages.edit');
    Route::group(['prefix' => 'messages'], function () {
        Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
        Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
        Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
        Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
        Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
    });
});

Route::group(['middleware' => ['auth', 'verified']], function() {

    Route::resource('companies', 'CompaniesController')->except(['index', 'show']);

    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::post('projects/addUser', 'ProjectsController@addUser')->name('projects.addUser');
    Route::delete('projects/member/{project_id}/{user_id}', 'ProjectsController@deleteMember')->name('projects.deleteMember');
    Route::resource('projects', 'ProjectsController')->except(['index', 'show']);

    Route::get('tasks/create/{project_id?}', 'TasksController@create');
    Route::post('tasks/addUser', 'TasksController@addUser')->name('tasks.addUser');
    Route::delete('tasks/member/{task_id}/{user_id}', 'TasksController@deleteMember')->name('tasks.deleteMember');
    Route::resource('tasks', 'TasksController')->except(['index', 'show']);
});

Route::group(['middleware' => ['auth', 'verified', 'admin']], function() {
    Route::get('companies/all', 'CompaniesController@all')->name('admin.companies');
    Route::get('projects/all', 'ProjectsController@all')->name('admin.projects');
    Route::get('tasks/all', 'TasksController@all')->name('admin.tasks');
    Route::delete('users/{user}', 'UsersController@destroy')->name('users.destroy');
    Route::get('users/all', 'UsersController@all')->name('admin.users');
    Route::get('comments/all', 'CommentsController@all')->name('admin.comments');
});

Route::get('search', 'SearchController@search')->name('search');

Route::get('companies', 'CompaniesController@index')->name('companies.index');
Route::get('companies/{company}', 'CompaniesController@show')->name('companies.show');

Route::get('projects', 'ProjectsController@index')->name('projects.index');
Route::get('projects/{project}', 'ProjectsController@show')->name('projects.show');

Route::get('tasks', 'TasksController@index')->name('tasks.index');
Route::get('tasks/{task}', 'TasksController@show')->name('tasks.show');

Route::get('users/{user}', 'UsersController@show')->name('users.show');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = [
        'name',
        'description',
        'kind',
        'priority',
        'days',
        'project_id',
        'user_id',
        'company_id'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function project()
    {
        return $this->belongsTo(Project::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public static function findByUserId($user_id)
    {
        $tasks = Task::where('user_id', $user_id)->get();
        return $tasks;
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TasksRequest;
use App\Mail\UserAttachedToTask;
use App\Mail\UserRemovedFromTask;
use App\Models\Comment;
use App\Models\Project;
use App\Models\Task;
use App\Models\TaskUser;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

class TasksController extends Controller
{
    public function deleteMember($task_id, $user_id)
    {
        TaskUser::findOneByUserIdAndTaskId($user_id, $task_id)->delete();
        $user = User::find($user_id);
        $task = Task::find($task_id);
        Mail::to($user)->send(new UserRemovedFromTask($task));

        return response()->json(['message' => 'Task member was removed and was notified via email']);
    }

    public function addUser(Request $request)
    {
        $task = Task::find($request->input('task_id'));
        if (Auth::user()->id == $task->user_id) {
            $user = User::where('email', $request->input('email'))->first();

            if (!$user) {
                return redirect()->route('tasks.show', ['task' => $task])
                    ->with('errors', $request->input('email').' doesnt exist');
            }

            $taskUser = TaskUser::findOneByUserIdAndTaskId($user->id, $task->id);

            if ($taskUser) {
                return redirect()->route('tasks.show', ['task' => $task])
                    ->with('errors', $request->input('email') . ' is already working on this Task');
            }

            $task->users()->attach($user->id);
            Mail::to($user)->send(new UserAttachedToTask($task));

            return redirect()->route('tasks.show', ['task' => $task])
                ->with('success', $request->input('email') . ' was added for this Task successfully and notified via email');
        }

        return redirect()->route('tasks.show', ['task' => $task])
            ->with('errors', 'Invalid action');
    }

    public function all()
    {
        $tasks = Task::all();
        return view('admin.tasks', ['tasks' => $tasks]);
    }

    public function index()
    {
        $tasks = null;
        if (Auth::check()) {
            $tasks = Task::findByUserId(Auth::id());
        }
        return view('tasks.index', ['tasks' => $tasks]);
    }


    public function create($project_id = null)
    {
        $projects = null;
        if (!$project_id) {
            $projects = Project::findByUserId(Auth::id());
        }

        return view('tasks.create', ['project_id' => $project_id, 'projects' => $projects]);
    }


    public function store(TasksRequest $request)
    {
        $request->validated();

        $task = Task::create([
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'kind' => $request->input('kind'),
            'priority' => $request->input('priority'),
            'days' => $request->input('days'),
            'project_id' => $request->input('project_id'),
            'user_id' => Auth::id()
        ]);

        if ($task) {
            return redirect()->route('tasks.show', ['task' => $task->id])
                ->with('success' , 'Task created successfully');
        }

        return back()->withInput()->with('errors', 'Error creating new Task');
    }


    public function show(Task $task)
    {
        $itemsPerPage = 3;
        $comments = Comment::findByIdAndType('App\Models\Task',  $task->id, $itemsPerPage);
        $creator = User::find($task->user_id);
        $project = Project::find($task->project_id);

        return view('tasks.show', ['task' => $task, 'comments' => $comments, 'creator' => $creator, 'project' => $project]);
    }


    public function edit(Task $task)
    {
        return view('tasks.edit', ['task' => $task]);
    }

    public function update(TasksRequest $request, Task $task)
    {
        $request->validated();

        $taskUpdate = $task->update([
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'kind' => $request->input('kind'),
            'priority' => $request->input('priority'),
            'days' => $request->input('days'),
        ]);

        if ($taskUpdate) {
            return redirect()->route('tasks.show', ['task' => $task->id])
                ->with('success' , 'Task updated successfully');
        }

        return back()->withInput();
    }

    public function destroy(Task $task)
    {
        $task->delete();
        Comment::deleteByTypeAndId('App\Models\Task', $task->id);

        if (Auth::user()->role_id == 1) {
            return redirect()->route('admin.tasks')->with('success' , 'Task deleted successfully');
        }

        return redirect()->route('tasks.index')->with('success' , 'Task deleted successfully');
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9">
        @if ($project_id == null && count($projects) == 0)
            <div class="alert alert-dismissable alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong> Task cannot be created before Project. Try to create any Project first.</strong>
            </div>
        @endif

        <h3 class="text-center">Create new Task</h3>
        <form method="post" action="{{ route('tasks.store') }}">
            @csrf

            <div class="form-group">
                <label for="task-name">Name:</label>
                <input placeholder="Enter name"
                       id="task-name"
                       required
                       name="name"
                       spellcheck="false"
                       class="form-control form-control-lg"
                />
            </div>

            <div class="form-group">
                <label for="task-description">Description:</label>
                <textarea placeholder="Enter description"
                          id="task-description"
                          name="description"
                          rows="5" spellcheck="false"
                          class="form-control form-control-lg"></textarea>
            </div>

            @if ($projects == null)
                <input
                    class="form-control form-control-lg"
                    type="hidden"
                    name="project_id"
                    value="{{ $project_id }}"
                />
            @endif

            @if ($projects != null && count($projects) != 0)
                <div class="form-group">
                    <label>Select Project:</label>
                    <select name="project_id" class="form-control form-control-lg">
                        @foreach($projects as $project)
                            <option value="{{ $project->id }}">{{ $project->name }}</option>
                        @endforeach
                    </select>
                </div>
            @endif

            <div class="form-group">
                <label for="task-kind">Type: </label>
                <select name="kind" id="task-kind" class="form-control form-control-lg">
                    <option>Proposal</option>
                    <option>Enhancement</option>
                    <option>Bug</option>
                </select>
            </div>

            <div class="form-group">
                <label for="task-priority">Priority: </label>
                <select name="priority" id="task-priority" class="form-control form-control-lg">
                    <option>Trivial</option>
                    <option>Minor</option>
                    <option>Major</option>
                    <option>Critical</option>
                </select>
            </div>

            <div class="form-group">
                <label for="task-days">Days:</label>
                <input placeholder="Enter days"
                       id="task-days"
                       type="number"
                       min="1"
                       max="1000"
                       required
                       name="days"
                       spellcheck="false"
                       class="form-control form-control-lg"
                />
            </div>

            <div class="form-group text-center">
                <input type="submit" class="btn btn-primary btn-block" id="submit"
                       value="Submit"/>
            </div>

        </form>
    </div>

    <div class="col-sm-3">
        <ul class="list-group">
            <h4>Actions: </h4>
            <li class="list-group-item"><a href="/tasks">All Tasks</a></li>
        </ul>
    </div>
    @if ($project_id == null && count($projects) == 0)
        <script>
            $('#submit').attr('disabled', 'disabled');
        </script>
    @endif
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9">
        <form method="post" action="{{ route('tasks.update', [$task->id]) }}">
            @csrf
            @method('put')

            <div class="form-group">
                <label for="task-name">Name:</label>
                <input   placeholder="Enter name"
                         id="task-name"
                         required
                         name="name"
                         spellcheck="false"
                         class="form-control form-control-lg"
                         value="{{ $task->name }}"
                />
            </div>

            <div class="form-group">
                <label for="task-description">Description:</label>
                <textarea placeholder="Enter description"
                          id="task-description"
                          name="description"
                          rows="5" spellcheck="false"
                          class="form-control form-control-lg"></textarea>
            </div>

            <div class="form-group">
                <label for="task-kind">Type: </label>
                <select name="kind" id="task-kind" class="form-control form-control-lg">
                    <option>Enhancement</option>
                    <option>Bug</option>
                    <option>Proposal</option>
                </select>
            </div>

            <div class="form-group">
                <label for="task-priority">Priority: </label>
                <select name="priority" id="task-priority" class="form-control form-control-lg">
                    <option>Trivial</option>
                    <option>Minor</option>
                    <option>Major</option>
                    <option>Critical</option>
                </select>
            </div>

            <div class="form-group">
                <label for="task-days">Days:</label>
                <input   placeholder="Enter days"
                         id="task-days"
                         type="number"
                         min="1"
                         max="100"
                         required
                         name="days"
                         spellcheck="false"
                         class="form-control form-control-lg"
                />
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary btn-block"
                       value="Submit"/>
            </div>
        </form>
    </div>

    <div class="col-sm-3">
        <ul class="list-group">
            <h4>Actions: </h4>
            <li class="list-group-item"><a href="/tasks/{{ $task->id }}">View Task</a></li>
            <li class="list-group-item"><a href="/tasks">My Tasks</a></li>
        </ul>
    </div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-6 col-lg-6 center">
        <div class="card">
            <div class="card-header text-center text-white bg-primary"> Tasks <a class="pull-right btn btn-primary" href="/tasks/create">Create new</a></div>
            <div class="card-body">
                <ul class="list-group">
                    @if (!is_null($tasks) && count($tasks) > 0)
                        @foreach($tasks as $task)
                            <li class="list-group-item">
                                <a href="/tasks/{{ $task->id }}"> {{ $task->name }} </a>
                            </li>
                        @endforeach
                    @else
                        <li class="list-group-item">
                            <p class="text-center">No Tasks yet</p>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9">
        <div class="jumbotron text-center">
            <h2>{{ $task->name }}</h2>
            <h4><i>Type:</i> <mark>{{ $task->kind }}</mark></h4>
            <h4><i>Priority:</i> <mark>{{ $task->priority }}</mark></h4>
            <p class="lead">Days: <span class="underline">{{ $task->days }}</span></p>
            <p class="text-success">created at {{ $task->created_at }}</p>
            <p class="lead">by <a href="/users/{{ $creator->id }}">{{ $creator->email }}</a> </p>
            <p class="lead">Project title: <a href="/projects/{{ $project->id }}">{{ $project->name }}</a></p>
        </div>
        <br>
        @if (!empty ($task->description))
            <h4 class="text-center"> Task description </h4>
            <p>{{ $task->description }}</p>
            <br><br>
        @endif

        @include('partials.comments')

        @include('partials.new-comment-form', ["type" => "App\Models\Task", "id" => $task->id])

    </div>

    <div class="col-sm-3">
        <div class="sidebar-module">
            <h4>Actions: </h4>
            <ol class="list-unstyled">
                @if (Auth::check() && ($task->user_id == Auth::user()->id || Auth::user()->role_id == 1))
                    <li><a href="/tasks/{{ $task->id }}/edit"><i class="fas fa-edit"></i> Edit</a></li>
                @endif
                <li><a href="/tasks/create"><i class="fas fa-plus-circle"></i> Create new Task</a></li>
                <li><a href="/tasks"><i class="fas fa-briefcase"></i> My Tasks</a></li>
                <br>
                @if (Auth::check() && ($task->user_id == Auth::user()->id || Auth::user()->role_id == 1))
                    <li>
                        <a href="#" class="js-delete">
                            <i class="fas fa-trash"></i> Delete
                        </a>

                        <form id="delete-form" action="{{ route('tasks.destroy', [$task->id]) }}"
                              method="POST" class="hidden">
                            @method('delete')
                            @csrf
                        </form>
                    </li>
                @endif
            </ol>

            @if (Auth::check() && ($task->user_id == Auth::user()->id || Auth::user()->role_id == 1))
                <h5>Add members:</h5>
                <form id="add-user" action="{{ route('tasks.addUser') }}" method="POST">
                    @csrf

                    <div class="input-group">
                        <input class="form-control" name="task_id" value="{{ $task->id }}" type="hidden">
                        <input type="text" class="form-control" id="email" required name="email"
                               placeholder="Email">

                        <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">Add!</button>
                            </span>
                    </div>
                </form>
                <br>
            @endif

            @if (count($task->users) > 0)
                <h5>Current members:</h5>
                <ul class="list-group">
                    @foreach($task->users as $user)
                        <li class="list-group-item"><a href="/users/{{$user->id}}">{{ $user->email }}</a>
                            @if (Auth::check() && $task->user_id == Auth::id())
                                <button type="button" class="btn btn-primary btn-sm js-delete-task-member btn-danger float-right"
                                        data-task_id="{{ $task->id }}" data-user_id="{{ $user->id }}">Remove
                                </button>
                            @endif
                        </li>
                    @endforeach
                </ul>
            @else
                <h6 class="text-muted">No active members yet</h6>
            @endif
        </div>
    </div>
@endsection